(custom-set-variables
 '(LaTeX-indent-level 4)
 '(TeX-brace-indent-level 4)
 '(auto-save-default nil)
 '(bar-cursor 2)
 '(bkup-backup-directory-info (quote ((".*" "~/.xemacs/backup" ok-create full-path))) nil (backup-dir))
 '(buffers-tab-face (quote buffers-tab))
 '(buffers-tab-max-size 100)
 '(buffers-tab-switch-to-buffer-function (quote switch-to-buffer))
 '(c-basic-offset 4)
 '(c-default-style (quote ((java-mode . "java") (other . "bsd"))))
 '(column-number-mode t)
 '(cperl-indent-level 4)
 '(cperl-invalid-face (quote default))
 '(dired-find-subdir t)
 '(dired-no-confirm (quote (load create-top-dir)))
 '(drag-divider-event-lag 50)
 '(ecb-options-version "2.31")
 '(ediff-window-setup-function (quote ediff-setup-windows-plain))
 '(font-lock-mode t nil (font-lock))
 '(get-frame-for-buffer-default-instance-limit nil)
 '(gutter-buffers-tab-visible-p t)
 '(highlight-current-line-globally t nil (highlight-current-line))
 '(lazy-shot-mode t nil (lazy-shot))
 '(line-number-mode t)
 '(mail-user-agent (quote sendmail-user-agent))
 '(modeline-3d-p t)
 '(modeline-scrolling-method (quote scrollbar))
 '(ps-print-color-p nil)
 '(tabbar-mode nil t)
 '(toolbar-visible-p nil)
 '(truncate-lines t))
(custom-set-faces
 '(default ((t (:family "Dejavu Sans Mono" :stipple nil :background "gray12" :foreground "green" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal))) t)
 '(cperl-array-face ((((class color) (background light)) (:foreground "Blue" :bold t))))
 '(cperl-hash-face ((((class color) (background light)) (:foreground "Red" :bold t :italic t))))
 '(font-lock-comment-face ((((class color) (background light)) (:foreground "chocolate1"))))
 '(highlight-current-line-face ((t (:background "black"))))
 '(hyper-apropos-hyperlink ((((class color) (background light)) (:underline t))))
 '(region ((t (:inverse-video nil))))
 '(zmacs-region ((t (:background "blue"))) t))
